"""empty message

Revision ID: b12308175603
Revises: 8d8ec569eaf7
Create Date: 2020-03-29 01:18:52.108832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12308175603'
down_revision = '8d8ec569eaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.alter_column('post_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_tags', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
